### ISSUE TITLE
Update version numbers to 3.26.0 for features and bundles

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn.tasks#9]
All the features should be aligned to version numbers to 3.26.0 
* to simplify support
* to identify circular dependencies

**Comment by BeckerFrank** [comment]
connector-bugzilla-rest was never really released. Maybe we can remove this and focus on the GitHub and GitLab connectors

**Comment by ruspl-afed** [comment]
Do we already have an issue for it?

**Comment by ruspl-afed** [comment]
Done with #10
